config/routes.rb
Rails.application.routes.draw do
	resources :episodes
	resources :categories
	resources :series
	devise_for :users, :controllers => {registrations: 'registrations'} 
	root 'home#index'
	resources :users

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/episode.rb
class Episode < ApplicationRecord
	#belongs_to :series
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
  before_action :set_episode, only: [:show, :edit, :update, :destroy]

  # GET /episodes
  # GET /episodes.json
  def index
    @episodes = Episode.all
  end

  # GET /episodes/1
  # GET /episodes/1.json
  def show
  end

  # GET /episodes/new
  def new
    @episode = Episode.new
  end

  # GET /episodes/1/edit
  def edit
  end

  # POST /episodes
  # POST /episodes.json
  def create

    @episode = Episode.new(episode_params.merge(:user => current_user.id))

    respond_to do |format|
      if @episode.save
        format.html { redirect_to series_index_url, notice: 'Episode was successfully created.' }
        format.json { render :show, status: :created, location: @episode }
      else
        format.html { render :new }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /episodes/1
  # PATCH/PUT /episodes/1.json
  def update
    respond_to do |format|
      if @episode.update(episode_params)
        format.html { redirect_to @episode, notice: 'Episode was successfully updated.' }
        format.json { render :show, status: :ok, location: @episode }
      else
        format.html { render :edit }
        format.json { render json: @episode.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /episodes/1
  # DELETE /episodes/1.json
  def destroy
    @episode.destroy
    respond_to do |format|
      format.html { redirect_to episodes_url, notice: 'Episode was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_episode
      @episode = Episode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def episode_params
      params.require(:episode).permit(:name, :description, :series, :season, :episode_number)
    end
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(episode) do |f| %>
  <% if episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% episode.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="ui form" style="padding: 50px 400px;">
  <div class="field">
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>

  <div class="field">
    <%= f.label :description%>
    <%= f.text_field :description%>
  </div>

  <p>
    <%= f.select :series, Series.all.collect {|x| [x.name, x.id ]}, {:include_blank => "Select One"} %> </br>
  </p>

  <div class="field">
    <%= f.label :season%>
    <%= f.text_field :season%>
  </div>

  <div class="field">
    <%= f.label :episode_number%>
    <%= f.text_field :episode_number%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing Episode</h1>

<%= render 'form', episode: @episode %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="padding-left: 45%; margin-top: 50px; font-size: 30px;">Episodes</h1>

<table class="ui definition table" style="margin-top: 50px;">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="row">
  <div class="ui button" style="text-align: center; vertical-align: middle; margin-left: 42%; margin-top: 30px; width: 200px; height: 40px; background-color: lightgrey;">
        <%= link_to 'New Episode', new_episode_path %>
    </div>

app/views/episodes/new.html.erb
<h1 style="padding-left: 45%; margin-top: 50px; font-size: 30px;">New Episode</h1>

<%= render 'form', episode: @episode %>


<div class="ui button" style="text-align: center; vertical-align: middle; width: 200px; height: 40px; background-color: lightgrey; margin-left: 43%;">
       <%= link_to 'Back', episodes_path %>
</div>

app/views/episodes/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_episode_path(@episode) %> |
<%= link_to 'Back', episodes_path %>