config/routes.rb
Rails.application.routes.draw do
	resources :episodes
	resources :categories
	resources :series
	devise_for :users, :controllers => {registrations: 'registrations'} 
	root 'home#index'
	resources :users

  	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: [:show, :edit, :update, :destroy]

  # GET /series
  # GET /series.json
  def index
    @series = Series.all
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params.merge(:user => current_user.id))

    respond_to do |format|
      if @series.save
        format.html { redirect_to series_index_url, notice: 'Series was successfully created.' }
        format.json { render :index, status: :created, location: @series }
      else
        format.html { render :new }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1
  # PATCH/PUT /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to @series, notice: 'Series was successfully updated.' }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url, notice: 'Series was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:name, :description, :category, :season, :user)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_for(series) do |f| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="ui form" style="padding: 50px 400px;">
  <div class="field">
    <%= f.label :name%>
    <%= f.text_field :name%>
  </div>

  <div class="field">
    <%= f.label :description%>
    <%= f.text_field :description%>
  </div>

  <p>
    <%= f.select :category, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %> </br>
  </p>

  <div class="field">
    <%= f.label :season%>
    <%= f.text_field :season%>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1 style="padding-left: 45%; margin-top: 50px; font-size: 30px;">Series</h1>
<table class="ui definition table" style="margin-top: 50px;">
  <thead>
    <tr>
      <th>Serie</th>
      <th>Season</th>
      <th>Category</th>
      <th>Creator</th>
      <th>Description</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |serie| %>
      <%if !user_signed_in?%>
          <% if User.find(serie.user).admin %>
              <tr>
                <td><%= serie.name %></td>
                <td><%= serie.season %></td>
                <td><%= Category.find(serie.category).name %></td>
                <td><%= serie.description %> </td>
                <td> Admin </td>
              </tr>
            <%end%>

        <%elsif User.find(current_user.id).admin %>
            <tr>
              <td><%= serie.name %></td>
              <td><%= serie.season %></td>
              <td><%= Category.find(serie.category).name %></td>
              <td><%= serie.description %> </td>
              <td><%= User.find(serie.user).username %></td>
              <td><%= link_to 'Show', serie %> </td>
              <td><%= link_to 'Edit', edit_series_path(serie) %> </td>
              <td><%= link_to 'Destroy', serie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>

      <% elsif User.find(serie.user).admin && current_user.id.to_s == serie.user%>
            <tr>
              <td><%= serie.name %></td>
              <td><%= serie.season %></td>
              <td><%= Category.find(serie.category).name %></td>
              <td><%= serie.description %> </td>
              <td><%= User.find(serie.user).username %></td>
              <td><%= link_to 'Show', series_path(serie) %> </td>
              <td><%= link_to 'Edit', edit_series_path(serie) %> </td>
              <td><%= link_to 'Destroy', serie, method: :delete, data: { confirm: 'Are you sure?' } %>
              </tr>
        <%elsif User.find(serie.user).admin  && current_user.id.to_s != serie.user%>
              <tr>
                <td><%= serie.name %></td>
                <td><%= serie.season %></td>
                <td><%= Category.find(serie.category).name %></td>
                <td><%= User.find(serie.user).username %></td>
                <td><%= serie.description %> </td>
                <td><%= link_to 'Show', serie %></td>
              </td>
        <%elsif current_user.id.to_s == serie.user %>
            <tr>
              <td><%= serie.name %></td>
              <td><%= serie.season %></td>
              <td><%= Category.find(serie.category).name %></td>
              <td><%= serie.description %> </td>
              <td><%= User.find(serie.user).username %></td>
              <td><%= link_to 'Show', serie %> </td>
              <td><%= link_to 'Edit', edit_series_path(serie) %> </td>
              <td><%= link_to 'Destroy', serie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>

        

        <% end %>


      <% end %>
  </tbody>
</table>

<br>
<div class="row">
  <% if user_signed_in? %>
    <div class="ui button" style="text-align: center; vertical-align: middle; margin-top: 30px; margin-left: 32.5%; width: 200px; height: 40px; background-color: lightgrey;">
        <%= link_to 'New Series', new_series_path %>
    </div>
  <%end%> 
  <div class="ui button" style="text-align: center; vertical-align: middle; margin-top: 30px; width: 200px; height: 40px; background-color: lightgrey;">
        <%= link_to 'Back', root_path %>
    </div>
  

</div>

app/views/series/new.html.erb
<h1 style="padding-left: 45%; margin-top: 50px; font-size: 30px;">New Series</h1>

<%= render 'form', series: @series %>

<div class="ui button" style="text-align: center; vertical-align: middle; width: 200px; height: 40px; background-color: lightgrey; margin-left: 43%;">
       <%= link_to 'Back', series_index_path %>
</div>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>
<h1 style="padding-left: 45%; margin-top: 50px; font-size: 30px;">Episodes</h1>


<table class="ui definition table" style="margin-top: 50px;">
  <thead>
    <!-- <tr>
      <th><% @series.name %></th>#No se como mostrar los valores
      <th><% @series.season %> </th>#No se como mostrar los valores

      <th colspan="3"></th>
    </tr> -->
  <tr>
    <th>Nombre de episodio</th>
    <th>descripcion de episodio</th>
    <th>Numero de episodio</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
    <% Episode.all.collect do |episode| %>
    <% if episode.season == @series.season && Series.find(episode.series).id == @series.id %>

      <% if User.find(@series.user).admin && current_user.id.to_s == @series.user%>
        <tr>
          <td><%= episode.name %></td>
          <td><%= episode.description %></td>
          <td><%= episode.episode_number %></td>
          <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
          <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %>
        </tr>

      <%elsif User.find(@series.user).admin  && current_user.id.to_s != @series.user%>
        <tr>
          <td><%= episode.name %></td>
          <td><%= episode.description %></td>
          <td><%= episode.episode_number %></td>
        </tr>

      <%elsif current_user.id.to_s == @series.user %>
        <tr>
          <td><%= episode.name %></td>
          <td><%= episode.description %></td>
          <td><%= episode.episode_number %></td>
          <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
          <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <%end%>
    <% end %>
  <% end %>

</tbody>
</table>

<div class="row">
  <% if user_signed_in? %>
    <div class="ui button" style="text-align: center; vertical-align: middle; margin-top: 30px; margin-left: 32.5%; width: 200px; height: 40px; background-color: lightgrey;">
        <%= link_to 'New Chapter', new_episode_path %>
    </div>
  <%end%> 
  <div class="ui button" style="text-align: center; vertical-align: middle; margin-top: 30px; width: 200px; height: 40px; background-color: lightgrey;">
        <%= link_to 'Back', series_index_path %>
    </div>